spring:
  jpa:
    hibernate:
#      ddlAuto: create-drop
      ddlAuto: update

  primary:
    datasource:
      #   data: classpath*:data-docker.sql
      driver: org.postgresql.Driver
      url: ${JDBC_DATABASE_URL}?reWriteBatchedInserts=true
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}
  replica:
    datasource:
      driver: org.postgresql.Driver
      url: ${JDBC_REPLICA_DATABASE_URL}?sslMode=require
      username: ${JDBC_REPLICA_DATABASE_USERNAME}
      password: ${JDBC_REPLICA_DATABASE_PASSWORD}

rtsearch:
  url: ${RT_SEARCH_URL}

server:
  port: 8080

hybrid:
  nodeUrl: ${ETHEREUM_RPC_URL}
  ownerPrivateKey: ${OWNER_PRIVATE_KEY}

  contracts:
    nameService:
      address: ${DNS_CONTRACT_ADDRESS}
      gasPrice: ${ETHEREUM_GAS_PRICE}
      gasLimit: ${ETHEREUM_GAS_LIMIT}

appoptics:
  serviceKey: ${APPOPTICS_SERVICE_KEY}
