spring:
  jpa:
    hibernate:
      ddlAuto: validate

  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

elastic:
  url: 'https://wa0p11xe8c:stzl1eu2s1@redwood-557957793.us-east-1.bonsaisearch.net'

flyway:
  baseline-on-migrate: true
  url: ${JDBC_DATABASE_URL}
  user: ${JDBC_DATABASE_USERNAME}
  password: ${JDBC_DATABASE_PASSWORD}
  locations: db/migration

hybrid:
  nodeUrl: https://ropsten.infura.io/
  ownerPrivateKey: ${OWNER_PRIVATE_KEY}

  contracts:
    nameService:
      address: ${DNS_CONTRACT_ADDRESS}
      gasPrice: ${ETHEREUM_GAS_PRICE}
      gasLimit: ${ETHEREUM_GAS_LIMIT}
