spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddlAuto: update

    connection:
      providerClass: org.hibernate.hikaricp.internal.HikariCPConnectionProvider

  datasource:
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000

    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

rtsearch:
  url: ${RT_SEARCH_URL}

flyway:
  enabled: false
  baseline-on-migrate: true
  url: ${JDBC_DATABASE_URL}
  user: ${JDBC_DATABASE_USERNAME}
  password: ${JDBC_DATABASE_PASSWORD}
  locations: db/migration

hybrid:
  nodeUrl: https://ropsten.infura.io/
  ownerPrivateKey: ${OWNER_PRIVATE_KEY}

  contracts:
    nameService:
      address: ${DNS_CONTRACT_ADDRESS}
      gasPrice: ${ETHEREUM_GAS_PRICE}
      gasLimit: ${ETHEREUM_GAS_LIMIT}
