spring:
  jpa:
    hibernate:
#      ddlAuto: create-drop
      ddlAuto: update

  datasource:
#   data: classpath*:data-docker.sql
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

rtsearch:
  url: ${RT_SEARCH_URL}

server:
  port: 8080

hybrid:
  nodeUrl: ${ETHEREUM_RPC_URL}
  ownerPrivateKey: ${OWNER_PRIVATE_KEY}

  contracts:
    nameService:
      address: ${DNS_CONTRACT_ADDRESS}
      gasPrice: ${ETHEREUM_GAS_PRICE}
      gasLimit: ${ETHEREUM_GAS_LIMIT}

appoptics:
  serviceKey: ${APPOPTICS_SERVICE_KEY}
