spring:
  jpa:
    hibernate:
      ddlAuto: update

  primary:
    datasource:
      driver: org.postgresql.Driver
      url: ${JDBC_DATABASE_URL}?reWriteBatchedInserts=true&sslMode=require
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}
  replica:
    datasource:
      driver: org.postgresql.Driver
      url: ${JDBC_REPLICA_DATABASE_URL}?sslMode=require
      username: ${JDBC_REPLICA_DATABASE_USERNAME}
      password: ${JDBC_REPLICA_DATABASE_PASSWORD}

logstash:
  endpoint: ${LOGSTASH_ENDPOINT}

rtsearch:
  url: ${RT_SEARCH_URL}

hybrid:
  nodeUrl: https://ropsten.infura.io/
  ownerPrivateKey: ${OWNER_PRIVATE_KEY}

  contracts:
    nameService:
      address: ${DNS_CONTRACT_ADDRESS}
      gasPrice: ${ETHEREUM_GAS_PRICE}
      gasLimit: ${ETHEREUM_GAS_LIMIT}

appoptics:
  serviceKey: ${APPOPTICS_SERVICE_KEY}