# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: base-node-staging
spec:
  replicas:
  template:
    metadata:
      name: base-node-service
      labels:
        app: base-node
        role: backend
        env: staging
    spec:
      containers:
        - name: service
          image: gcr.io/bitclave-jenkins-ci/base-node
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
          env:
            - name: PROFILE
              value: "product"

            - name: WALLET_CONTRACT_ADDRESS
              value: "0x56c38d117f92ed0501a9f7ee39abf9089988b6e0"

            - name: BASE_CONTRACT_ADDRESS
              value: "0x9a297a3abaaa1ae4f2a77d9b2de4afbbe8b36d56"

            - name: ACCOUNT_CONTRACT_ADDRESS
              value: "0x56c38d117f92ed0501a9f7ee39abf9089988b6e0"

            - name: DNS_CONTRACT_ADDRESS
              value: "0x39e31ddecd716a8bf297d5d89b76d80514aed2c8"

            - name: ETHEREUM_GAS_LIMIT
              value: "4000000"

            - name:  ETHEREUM_GAS_PRICE
              value: "9000000"

          envFrom:
            - secretRef:
                name: secret-staging-base-node

          imagePullPolicy: Always
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 80
          # command: ["sh", "-c", "app -frontend=true -backend-service=http://gceme-backend:8080 -port=80"]
          ports:
            - name: api
              containerPort: 8080
